// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltytyllgshxbxbxdarog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0eXR5bGxnc2h4YnhieGRhcm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQ2OTUsImV4cCI6MjA2NTc1MDY5NX0.r0q5M96KsGLoqVrHsqQ0_-66jHXTU2iNGudL74xkEVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);